In [2]:
# ndarray
import numpy as np

In [6]:
arr=np.array([1,2,3,4,5], dtype="float")
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1. 2. 3. 4. 5.]


In [14]:
#2D array
array=np.array([[2,4,6,8],[1,3,5,7]])
print(array)
arr.shape

[[2 4 6 8]
 [1 3 5 7]]


(2, 4)

In [16]:
print(array[0][3])
print(array[0][2:3])

8
[6]


In [3]:
array=np.array([[2,4,6,8],[1,3,5,7]])
print(np.sum(array))
print(np.mean(array))
print(np.min(array))
print(np.max(array))


36
4.5
1
8


In [4]:
array1=np.array([2,4,6,8])
array2=np.array([[1],[3],[5],[7]])
print(array1)
print(array2)
result=np.dot(array1,array2)
print(result)

[2 4 6 8]
[[1]
 [3]
 [5]
 [7]]
[100]


In [6]:
#Pandas
# diff between serie and dataframe
#csv semicolon and colon ->dataset
df.loc['snow']
df.

In [11]:
import pandas as pd
wheather={
    "day": ['1/02/2017', '21/03/2017','17/03/2017'],
    "temperature": [30,25,27],
    "windspeed": [6,7,8],
    "event": ["rain", "dry","Sunny"]
}

ab=pd.DataFrame(wheather)
print(ab)
df=pd.read_csv("weather_data.csv")
df[1:3]
df.columns
type(df['day'])
df["day"]
df[["day" , "temperature"]]
df["day"] [(df["temperature"]>30) | (df['event']=="sunny")] 
df["event"].max
df["temperature"].max
df.describe()

          day  temperature  windspeed  event
0   1/02/2017           30          6   rain
1  21/03/2017           25          7    dry
2  17/03/2017           27          8  Sunny


temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [29]:
df=pd.read_csv("winequality-white.csv", sep=";")
type(df)
df.head(5)

<bound method DataFrame.info of       fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020

In [31]:
df.info

<bound method DataFrame.info of       fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020

In [18]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [32]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     5.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.090000     0.410000     9.500000     5.000000  
50%       3.180000     0.470000    10.400000     6.000000  
75%       3.280000     0.550000    11.400000     6.000000  
max       3.820000     1.080000    14.200000     9.000000

In [41]:
df[df["quality"]>=7.2]


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
17              6.2             0.660         0.48             1.2      0.029   
20              6.2             0.660         0.48             1.2      0.029   
22              6.8             0.260         0.42             1.7      0.049   
68              6.7             0.230         0.31             2.1      0.046   
74              6.7             0.230         0.31             2.1      0.046   
...             ...               ...          ...             ...        ...   
4765            5.2             0.300         0.34             1.5      0.038   
4766            6.4             0.320         0.25             5.0      0.055   
4786            4.4             0.320         0.39             4.3      0.030   
4787            3.9             0.225         0.40             4.2      0.030   
4802            5.8             0.280         0.34             2.2      0.037   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
17                   29.0                  75.0  0.98920  3.33       0.39   
20                   29.0                  75.0  0.98920  3.33       0.39   
22                   41.0                 122.0  0.99300  3.47       0.48   
68                   30.0                  96.0  0.99260  3.33       0.64   
74                   30.0                  96.0  0.99260  3.33       0.64   
...                   ...                   ...      ...   ...        ...   
4765                 18.0                  96.0  0.98942  3.56       0.48   
4766                 28.0                 138.0  0.99171  3.27       0.50   
4786                 31.0                 127.0  0.98904  3.46       0.36   
4787                 29.0                 118.0  0.98900  3.57       0.36   
4802                 24.0                 125.0  0.98986  3.36       0.33   

      alcohol  quality  
17       12.8        8  
20       12.8        8  
22       10.5        8  
68       10.7        8  
74       10.7        8  
...       ...      ...  
4765     13.0        8  
4766     12.4        8  
4786     12.8        8  
4787     12.8        8  
4802     12.8        8  

[180 rows x 12 columns]

In [43]:
df[df["alcohol"]>= 13.0]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
701             5.9             0.340         0.22             2.4      0.030   
1099            5.8             0.290         0.21             2.6      0.025   
1238            7.1             0.440         0.37             2.7      0.041   
1242            8.1             0.430         0.42             6.6      0.033   
1243            7.1             0.440         0.37             2.7      0.041   
...             ...               ...          ...             ...        ...   
4837            6.5             0.280         0.38             7.8      0.031   
4863            6.2             0.360         0.32             4.0      0.036   
4865            6.2             0.355         0.35             2.0      0.046   
4867            5.3             0.600         0.34             1.4      0.031   
4887            6.2             0.410         0.22             1.9      0.023   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
701                  19.0                 135.0  0.98940  3.41       0.78   
1099                 12.0                 120.0  0.98940  3.39       0.79   
1238                 35.0                 128.0  0.98960  3.07       0.43   
1242                 36.0                 141.0  0.99180  2.98       0.39   
1243                 35.0                 128.0  0.98960  3.07       0.43   
...                   ...                   ...      ...   ...        ...   
4837                 54.0                 216.0  0.99154  3.03       0.42   
4863                 44.0                  92.0  0.98936  3.20       0.50   
4865                 31.0                  95.0  0.98822  3.06       0.46   
4867                  3.0                  60.0  0.98854  3.27       0.38   
4887                  5.0                  56.0  0.98928  3.04       0.79   

      alcohol  quality  
701      13.9        7  
1099     14.0        7  
1238     13.5        7  
1242     13.3        7  
1243     13.5        7  
...       ...      ...  
4837     13.1        6  
4863     13.3        7  
4865     13.6        6  
4867     13.0        6  
4887     13.0        7  

[138 rows x 12 columns]

In [44]:
df[df["pH"]<3.5]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[4742 rows x 12 columns]

In [52]:
#Lab Tasks
df=pd.read_csv("nyc_weather.csv", sep=",")
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN   
1                10           7.0               0           3       NaN   
2                10           8.0               0           1       NaN   
3                10           9.0               0           3       NaN   
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
8                 9           8.0               T           8      Rain   
9                 4           NaN             1.8           7      Rain   
10               10           NaN               0           1       NaN   
11               10           6.0               T           4       NaN   
12               10          10.0               0           0       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1       NaN   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
21                9           NaN            0.01      

In [55]:
df [(df["Temperature"]%2==0) & (df["WindSpeedMPH"] %2==1)]

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
1    1/2/2016           36        18        46                 30.02   
4    1/5/2016           20        -3        41                 30.57   
13  1/14/2016           30        12        47                 29.95   
18  1/19/2016           22         3        42                 30.03   
24  1/25/2016           34        18        54                 30.25   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
1                10           7.0               0           3    NaN   
4                10           5.0               0           0    NaN   
13               10           5.0               T           7    NaN   
18               10          11.0               0           1    NaN   
24               10           3.0               0           2    NaN   
29               10           7.0               0           0    NaN   
30               10           5.0               0           0    NaN   

    WindDirDegrees  
1              275  
4              333  
13             266  
18             293  
24             286  
29             257  
30             241

In [57]:
#df["WindSpeedMPH"].mean()
df[(df["WindSpeedMPH"]< df["WindSpeedMPH"].mean())]

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
11  1/12/2016           35        15        53                 29.85   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
16  1/17/2016           36        23        66                 29.78   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
27  1/28/2016           37        20        51                 29.90   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
11               10           6.0               T           4       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
16                8           6.0            0.05           6  Fog-Snow   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
23                8           6.0               T           3      Snow   
24               10           3.0               0           2       NaN   
27               10           5.0               0           1       NaN   
30               10           5.0               0           0       NaN   

    WindDirDegrees  
4              333  
5              259  
6              293  
7               79  
11             235  
13             266  
14             101  
16             345  
19             302  
20             312  
23             327  
24             286  
27             234  
30             241

In [64]:
df[(df["Events"]=="Snow")|(df["Events"]=="Rain") & (df["Temperature"] > 25)]

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
15  1/16/2016           47        37        70                 29.52   
17  1/18/2016           25         6        53                 29.83   
21  1/22/2016           26         6        41                 30.21   
23  1/24/2016           28        11        53                 29.92   
26  1/27/2016           41        22        45                 30.03   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
8                 9           8.0               T           8   Rain   
9                 4           NaN             1.8           7   Rain   
15                8           7.0            0.24           7   Rain   
17                9          12.0               T           2   Snow   
21                9           NaN            0.01           3   Snow   
23                8           6.0               T           3   Snow   
26               10           7.0               T           3   Rain   

    WindDirDegrees  
8               76  
9              109  
15             340  
17             293  
21              34  
23             327  
26             311